AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  consoleblockaccountchecker:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::753451452012:role/service-role/consoleblock-accountchecker-role-90gaznfc
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /checklist
            Method: ANY
